const { LitVocabTerm } = require("../lib/lit-vocab-term");
/**
  Generated by artifact generator [@lit/artifact-generator], version [0.1.0]
  as part of artifact: [@lit/generated-vocab-obelisk], version: [0.0.1]
  at 'Wednesday, October 16, 2019 7:57 AM'.

  Vocabulary built from input: [../../solid/solid.github.io/assets/misc/tutorials/quickstart-obelisk.ttl].

  
    The obelisk ontology aims at describing obelisks.
    
 */

const _NAMESPACE = "http://w3id.org/obelisk/ns/";
function _NS(localName) {
  return _NAMESPACE + localName;
}

const OBELISK = {
  PREFIX: "obelisk",
  NAMESPACE: _NAMESPACE,
  NS: _NS,

  // *****************
  // All the Classes.
  // *****************

  /**
   * An obelisk is a four-sided pilar with a pyramid-shaped top.
   */
  Obelisk: new LitVocabTerm(_NS("Obelisk"), localStorage, true)
    .addLabel("", `Obelisk`)
    .addComment(
      "",
      `An obelisk is a four-sided pilar with a pyramid-shaped top.`
    ),

  /**
   * An artist who sculpts obelisks.
   */
  Sculptor: new LitVocabTerm(_NS("Sculptor"), localStorage, true)
    .addLabel("", `Sculptor`)
    .addComment("", `An artist who sculpts obelisks.`),

  // *******************
  // All the Properties.
  // *******************

  /**
   * Relationship between an obelisk and the person who owns it, which is typically the person who ordered it, or to whom it was offered.
   */
  ownedBy: new LitVocabTerm(_NS("ownedBy"), localStorage, true)
    .addLabel("", `owned by`)
    .addComment(
      "",
      `Relationship between an obelisk and the person who owns it, which is typically the person who ordered it, or to whom it was offered.`
    ),

  /**
   * Relationship between an obelisk and the person who built it.
   */
  builtBy: new LitVocabTerm(_NS("builtBy"), localStorage, true)
    .addLabel("", `built by`)
    .addComment(
      "",
      `Relationship between an obelisk and the person who built it.`
    ),

  //
  // Marker allowing us put commas at the end of all lines above (only the last line does not have a comma).
  //
  END_OF_VOCAB: "End of vocab."
};

export default OBELISK;
